stages:
  - docker

before_script:
    - export CI_JOB_TIMESTAMP=$(date --utc -I'seconds' | sed 's/:/-/g' | sed 's/[+].*//')

docker:
  image: docker
  stage: docker
  only:
    - schedules
  services:
    - docker:dind
  script:
    - docker version
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_JOB_TIMESTAMP --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_JOB_TIMESTAMP
    - docker push $CI_REGISTRY_IMAGE:latest

